version: "3.9"

services:
  db:
    image: postgres:16
    container_name: carservice_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    env_file:
      - .env

  main-service:
    build:
      context: .
      dockerfile: backend/main-service/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/main-service:/app
      - ./frontend:/app/frontend  


volumes:
  db_data:
