FROM golang:1.24-alpine

WORKDIR /app

# Устанавливаем air
RUN go install github.com/air-verse/air@latest

# Копируем go.mod и go.sum
COPY backend/auth-service/go.mod .
COPY backend/auth-service/go.sum .
RUN go mod download

# Копируем весь код (а не только .air.toml)
COPY backend/auth-service ./

# Порт, если отличается от основного
EXPOSE 8081

CMD ["air"]
